#####
#
# This config file is used by the QP deploy script.
# First, remove the hardcoded contract address for the contract you want to be deployed.
# Then, after deployment, put the deployed addresses, in the config and send a commit
# tagged with UPDATE_QP_CONFIG
#
# Use $in the DeployerKeys section to get the value from an environment variable
# Note: If you provide `DeployerKeys.Owner`, you do NOT need to provide the `Owner`
#
#####

Owner:
DeployerContract: 
DeployerSalt: "0x65ff7961289d09280b311966c72b708989daabefb729d1a5b64fe72a9ad26049"
QuantumPortalGateway:
QuantumPortalPoc:
QuantumPortalLedgerMgr:
QuantumPortalAuthorityMgr:
QuantumPortalMinerMgr:
QuantumPortalStake:
FRM:
  97: "0xF3B61752E52B92BB0B8bF9eBb4FE487B8fD1047C"
  43113: "0xF3B61752E52B92BB0B8bF9eBb4FE487B8fD1047C"
  80001: "0xF3B61752E52B92BB0B8bF9eBb4FE487B8fD1047C"
  26026: "0x0000000000000000000000000000000000026026"
WFRM: "0x0000000000000000000000000000000000026026"
DeployerKeys:
  DeployerContract: $CONTRACT_DEPLOYER_KEY
  Qp: $QP_DEPLOYER_KEY
  Owner: $QP_DEPLOYER_KEY
